name: Apply

on:
  push:
    branches:
      - master

jobs:
  plan:
    name: Apply to GKE
    if: ${{ github.repository_owner == 'ExpidusOS' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: us-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
    strategy:
      matrix:
        region: [us-west1]
    steps:
      - uses: actions/checkout@v3
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/769178210270/locations/global/workloadIdentityPools/ci-pool/providers/github'
          service_account: 'github-ci@expidusos-infra.iam.gserviceaccount.com'
      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v1.0.2
        with:
          cluster_name: infra-${{ matrix.region }}
          location: ${{ matrix.region }}
      - name: Write variables
        run: |
          cat << EOF > terraform.tfvars
          region = "${{ matrix.region }}"
          aws_access_key_id = "${{ secrets.WASABI_ACCESS_KEY }}"
          aws_secret_access_key = "${{ secrets.WASABI_SECRET_KEY }}"
          EOF
      - name: Write s3.tfvars
        run: |
          cat << EOF > s3.tfvars
          key = "infra/${{ matrix.region }}/terraform.tfstate"
          access_key = "${{ secrets.WASABI_ACCESS_KEY }}"
          secret_key = "${{ secrets.WASABI_SECRET_KEY }}"
          EOF
      - name: Pull Terraform State
        run: |
          aws s3 --endpoint-url=https://s3.us-west-1.wasabisys.com cp s3://expidusos-ci/infra/${{ matrix.region }}/terraform.tfstate ./terraform.state
      - name: Apply
        uses: dflook/terraform-github-actions/terraform-apply@main
        with:
          auto_approve: true
      - name: Push Terraform State
        run: |
          aws s3 --endpoint-url=https://s3.us-west-1.wasabisys.com cp ./terraform.state s3://expidusos-ci/infra/${{ matrix.region }}/terraform.tfstate
